version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - C:\docker\vilaexplorer\odoo-db:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - 54320:5432
  web:
    image: odoo:16
    links:
      - db:db
    ports:
      - 8071:8069
    volumes:
      - C:\docker\vilaexplorer\odoo-data:/var/lib/odoo
      - C:\docker\vilaexplorer\addons:/mnt/extra-addons
      - C:\docker\vilaexplorer\config:/etc/odoo